---
title: "Create Seurat Objects from Cell Ranger Output"
author: "Donnacha Fitzgerald"
date: '2023-01-18'
output: html_document
---

This script was used to read count matrices from the CITE-Seq cell ranger out files and create a Seurat object for each sample. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(workflowr)
library(Seurat)
```

# Load CellRanger Output
```{r}
# List samples
SampleList <- read_excel("docs/SampleList.xlsx") %>%  filter(!row_number() %in% c(14, 15)) %>% filter(Entity != "CLL")
samples <- unique(SampleList$PatientID)
samples <- samples[samples %in% list.files("cellranger_out/")] %>% as.list() 
# Load count matrices from cell ranger output
loadmatrix <- function(x){
  data_dir <- paste0("cellranger_out/", x, "/outs/filtered_feature_bc_matrix")
  list.files(data_dir) # Should show barcodes.tsv.gz, features.tsv.gz, and matrix.mtx.gz
  data <- Read10X(data.dir = data_dir)
  # Add gene expression (RNA) and surface epitope (ADT) count data to the object
  seurat_object = CreateSeuratObject(counts = data$`Gene Expression`)
  seurat_object[['ADT']] = CreateAssayObject(counts = data$`Antibody Capture`)
  return(seurat_object)
}
seurat_objects <- lapply(samples, loadmatrix)
```


