---
title: "Create Processed Sample List"
author: "Donnacha Fitzgerald"
date: "16/02/2021"
output: html_document
---

This script serves to create a list of Seurat objects for all samples from the outputs of CreateSeurat.Rmd and SeuratProc.R. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(23)
```

# Load Packages and Data
```{r}
library(tidyverse)
library(Seurat)
```

```{r}
# Data for each Run in which each sample's RNA has been subject to QC filtering, log normalizaton, feature selection (n=2000), scaling, PCA and clustering is loaded. Cell cycle and mitochondrial gene effects were regressed out during scaling. ADT data has been subject to CLR normalization and scaling. See code/SeuratProcessing/ for details.
sobj <- readRDS("data/SeuratObjects/Runs/SeuratObjects1.rds")
sobj2 <- readRDS("data/SeuratObjects/Runs/SeuratObjects2.rds")
sobj3 <- readRDS("data/SeuratObjects/Runs/SeuratObjects3.rds")
sobj4 <- readRDS("data/SeuratObjects/Runs/SeuratObjects4.rds")
sobj5 <- readRDS("data/SeuratObjects/Runs/SeuratObjects5.rds")
sobj6 <- readRDS("data/SeuratObjects/Runs/SeuratObjects6.rds")
sobj7 <- readRDS("data/SeuratObjects/Runs/SeuratObjects7.rds")
sobj8 <- readRDS("data/SeuratObjects/Runs/SeuratObjects8.rds")
sobj9 <- readRDS("data/SeuratObjects/Runs/SeuratObjects9.rds")
sobj10 <- readRDS("data/SeuratObjects/Runs/SeuratObjects10.rds")
sobj11 <- readRDS("data/SeuratObjects/Runs/SeuratObjects11.rds")
```

# Create Sample List
```{r}
sobjList <- list(sobj$LN0050, sobj$LN0097, sobj2$LN0100, sobj2$LN0107, sobj3$LN0110, sobj3$LN0002, sobj3$LN0144, sobj3$LN0152, sobj4$LN0135, sobj4$LN0179, sobj4$LN0193, sobj4$LN0211, sobj5$LN0178, sobj5$LN0166, sobj6$LN0070, sobj6$LN0188, sobj6$LN0251, sobj6$LN0060, sobj7$LN0210, sobj7$LN0259, sobj7$LN0176, sobj7$LN0228, sobj8$LN0266, sobj8$LN0271, sobj8$LN0272, sobj8$LN0265, sobj9$LN0273, sobj9$LN0217, sobj9$LN0078, sobj9$LN0274, sobj10$LN0087, sobj10$LN0267, sobj10$LN0053, sobj10$LN0014, sobj11$LN0198, sobj11$LN0186, sobj11$LN0043, sobj11$LN0080)
```

```{r}
saveRDS(sobjList, file = "data/SeuratObjects/Lists/Run1-11.rds")
```


