---
title: "Seurat Processing - Run 1"
author: Roider Tobias
date: "`r doc_date()`"
output: 
    BiocStyle::html_document:
        toc: true
        self_contained: true
        toc_float: true
        code_download: true
        df_print: paged
        toc_depth: 3
    BiocStyle::pdf_document:
        toc: true
        toc_depth: 3
editor_options: 
  chunk_output_type: console
---

```{r options, include=FALSE, warning = FALSE}

library(knitr)
options(bitmapType = "cairo")
options(digits=3, width=80)
opts_chunk$set(echo=TRUE,tidy=FALSE,include=TRUE, size = 1,
               dev=c('png'), fig.small=FALSE, fig.height = 12,
               dpi = 300, cache = FALSE, warning = FALSE)

```

# Load packages and data
```{r message=FALSE}

library("readxl")
library("tidyverse")
library("Seurat")
source("code/SeuratProc.R")
source("code/QCplots.R")
load("output/sampleList.RData")

select <- dplyr::select
filter <- dplyr::filter
mutate <- dplyr::mutate
summarise <- dplyr::summarise

run_current <- "Run 1"

```

# Read samples of this run
```{r}

samples <- sampleList %>% filter(Run==run_current) %>% pull(PatientID)

samples

sobjs <- 
  lapply(samples, function(x){
  z <- list.files(path = "output/SeuratObjects_Raw", pattern = x, full.names = T)
  y <- readRDS(z)
  return(y)
})

```

# Process samples
## First sample
### Pre-Processing
```{r message=T}

sobj_tmp <- sobjs[[1]]

# Set processing parameters
nFeature_RNA_low=1300
percent.mt_top=10
nFeature_RNA_top=4000
dims.clustering=1:14
resolution.clustering = 0.4
dims.umap=1:14

# Basic QC plots (pre-processing)
VlnPlot_custom(sobj_tmp)
FeatureScatter_custom1(sobj_tmp)
FeatureScatter_custom2(sobj_tmp)  

# Run Seurat Processing
sobj_tmp <- SeuratProc1(sobj_tmp)

```

### Post-processing
```{r}

# Basic QC plots (post-processing)
VlnPlot_custom(sobj_tmp)
FeatureScatter_custom1(sobj_tmp)
FeatureScatter_custom2(sobj_tmp)  

# UMAP Plot
DimPlot_custom1(sobj_tmp)

# Check clustering by features or mito genes
FeaturePlot_custom1(sobj_tmp)

# Check doublets of B and T cells
FeaturePlot_custom2(sobj_tmp)

```

### Assign cell types by RNA cluster
```{r}

B <- c("0", "1", "3", "5")
Tc <- c("2", "4")
O <- c()

sobj_tmp$CT_rnaCluster <- 
  left_join(
    data.frame(sobj_tmp@meta.data),
    tibble(seurat_clusters=c(B, Tc, O) %>% as.factor(), 
           CT_rnaCluster=c(rep("B", length(B)), 
                           rep("T", length(Tc)), 
                           rep("Other", length(O))) %>% as.factor()
          )
    )%>% pull(CT_rnaCluster)

DimPlot_custom2(sobj_tmp)

sobjs[[1]] <- sobj_tmp

```

## Second sample
### Pre-Processing
```{r}

sobj_tmp <- sobjs[[2]]

# Set processing parameters
nFeature_RNA_low=200
percent.mt_top=10
nFeature_RNA_top=5000 
dims.clustering=1:14
resolution.clustering = 0.4
dims.umap=1:14

# Basic QC plots (pre-processing)
VlnPlot_custom(sobj_tmp)
FeatureScatter_custom1(sobj_tmp)
FeatureScatter_custom2(sobj_tmp)  

# Run Seurat Processing
sobj_tmp <- SeuratProc1(sobj_tmp)

```

### Post-Processing
```{r}

# Basic QC plots (post-processing)
VlnPlot_custom(sobj_tmp)
FeatureScatter_custom1(sobj_tmp)
FeatureScatter_custom2(sobj_tmp)  

# UMAP Plot
DimPlot_custom1(sobj_tmp)

# Exclude cluster 6
sobj_tmp <- subset(sobj_tmp,  idents = c(0:6, 8:9))

# Re-run Seurat Processing
sobj_tmp <- SeuratProc2(sobj_tmp)

# UMAP Plot
DimPlot_custom1(sobj_tmp)

# Check clustering by features or mito genes
FeaturePlot_custom1(sobj_tmp)

# Check doublets of B and T cells
FeaturePlot_custom2(sobj_tmp)

```

### Assign cell types by RNA cluster
```{r}

B <- c("0", "1", "2", "3", "6", "7")
Tc <- c("4", "5")
O <- c("8", "9")

sobj_tmp$CT_rnaCluster <- 
  left_join(
    data.frame(sobj_tmp@meta.data),
    tibble(seurat_clusters=c(B, Tc, O) %>% as.factor(), 
           CT_rnaCluster=c(rep("B", length(B)), 
                           rep("T", length(Tc)), 
                           rep("Other", length(O))) %>% as.factor()
          )
    )%>% pull(CT_rnaCluster)

DimPlot_custom2(sobj_tmp)

sobjs[[2]] <- sobj_tmp

```

# Final objects
```{r}

sobjs

```


# Save objects
```{r}

for(i in 1:length(sobjs)){
  saveRDS(object = sobjs[[i]], file = paste0("output/SeuratObjects_Proc/SeuratObject_Proc_", 
                                             samples[i], ".rds"))
  }

```
