---
title: "Figure S4: Multimodal subpopulation mapping of nodal B cell non-Hodgkin lymphomas, related to Figure 2"
author: "Donnacha Fitzgerald"
date: "2023-05-04"
output: html_document
---

This script generates the plots for Figure S4. See CelltypeAnnotation/MultimodalAnnotation.Rmd for the background to this analysis.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Set color palette for maturation states
mathue9 <- c("#ff707c",
              "#975F24",
              "#f8d058",
              "#41d5a8",
              "#006c0b",
              "#902395")
```

```{r}
library(tidyverse)
library(Seurat)
```

# Load Data

```{r}
# Load full CITE-Seq dataset from 51 lymph node samples, with mapping from the rLN reference
Combined <- readRDS("data/Objects/Combined_B_full.rds")
```

# Plot UMAPs

```{r, fig.width = 5, fig.height = 4.5}
# Group satellite cells (cluster 25 onward)
Idents(Combined) <- "MOFAclusters_res1"
new.cluster.ids <- c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "25", "25", "25", "25", "25", "25", "25", "25", "25", "25", "25")
names(new.cluster.ids) <- levels(Combined)
Combined <- RenameIdents(Combined, new.cluster.ids)
Combined$MOFAclusters_clean <- Idents(Combined)
DimPlot(Combined, 
        reduction = "umapMOFA",
        label = TRUE, repel = TRUE,
        label.box = TRUE, 
        label.color = "black",
        label.size = 5) +
  coord_fixed() +
  NoLegend() +
  ggtitle("Multimodal Clusters") + 
    theme(plot.title = element_text(size = 20, face = "bold", hjust = 0.5))
ggsave("figures/CelltypeMapping/MOFAumapClustersres1.pdf")
```

```{r, fig.width = 4, fig.height = 4}
DimPlot(Combined, group.by = "State", 
        reduction = "umapMOFA", cols = mathue9,
                label = TRUE, repel = TRUE,
        label.box = TRUE,
        label.color = "white") + 
  coord_fixed() +
  NoLegend() +
  theme(axis.title = element_text(size = 10),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
  ggtitle("Maturation State")
ggsave("figures/Supp10/MOFAumapMaturation.pdf", width = 4, height = 4)
```

```{r, fig.width = 4, fig.height = 4}
DimPlot(Combined, group.by = "Relapse", 
        reduction = "umapMOFA", shuffle = TRUE,
                label = TRUE, repel = TRUE,
        label.box = TRUE,
        label.color = "white") + 
  coord_fixed() +
    theme(axis.title = element_text(size = 10),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
  NoLegend() +
  ggtitle("Diagnosis vs Relapse")
ggsave("figures/Supp10/MOFAumapRelapse.pdf", width = 4, height = 4)
```

```{r, fig.width = 4, fig.height = 4}
DimPlot(Combined, group.by = "Entity", 
        reduction = "umapMOFA", shuffle = TRUE,
                label = TRUE, repel = TRUE,
        label.box = TRUE,
        label.color = "white") + 
  coord_fixed() +
    theme(axis.title = element_text(size = 10),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
  NoLegend() +
  ggtitle("Entity")
ggsave("figures/Supp10/MOFAumapEntity.pdf", width = 4, height = 4)
```

```{r, fig.width = 4, fig.height = 4}
DimPlot(Combined, group.by = "PatientID", 
        reduction = "umapMOFA", shuffle = TRUE,
                label = FALSE, repel = TRUE,
        label.box = TRUE,
        label.color = "white") + 
  coord_fixed() +
    theme(axis.title = element_text(size = 10),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
  NoLegend()
```

# Differential Expression Analysis

```{r}
Idents(Combined) <- "MOFAclusters_clean"
RNAmarkers <- FindAllMarkers(Combined, assay = "RNA")
saveRDS(RNAmarkers, "output/Bcells/CelltypeMapping/RNAmarkers_MOFAclusters.rds")
ADTmarkers <- FindAllMarkers(Combined, assay = "ADT", min.pct = 0, logfc.threshold = 0)
saveRDS(ADTmarkers, "output/Bcells/CelltypeMapping/ADTmarkers_MOFAclusters.rds")
```

## RNA

```{r, fig.width = 10, fig.height = 11}
RNAmarkers %>% group_by(cluster) %>% top_n(n = 5, wt = avg_log2FC) -> top5
AverageExpression(Combined, return.seurat = TRUE, assays = "RNA", slot = "scale.data") %>% DoHeatmap(features = top5$gene, assay = "RNA", slot = "scale.data", raster = FALSE, draw.lines = FALSE) +
  ggtitle("Differentially Expressed Genes by Subpopulation") +
  guides(color="none") + 
  theme(plot.title = element_text(size=22))
ggsave("figures/Supp10/MOFAclustersRNAheatmap.pdf")
```

## ADT

```{r, fig.width = 10, fig.height = 11}
ADTmarkers %>% group_by(cluster) %>% top_n(n = 5, wt = avg_log2FC) -> top5
AverageExpression(Combined, return.seurat = TRUE, assays = "ADT", slot = "scale.data") %>% DoHeatmap(features = top5$gene[!top5$gene %in% c(".hamsterIgG", ".ratIgG2b")], assay = "ADT", slot = "scale.data", raster = FALSE, draw.lines = FALSE) +
  ggtitle("Differentially Abundant Markers by Subpopulation") +
  guides(color="none") + 
  theme(plot.title = element_text(size=22))
ggsave("figures/Supp10/MOFAclustersRNAheatmap.pdf")
```
